[package]
name = "wormhole-cli"
version = "0.8.1"
edition = "2024"
publish = false

[dependencies]
magic-wormhole = { workspace = true, features = ["forwarding"] }
tokio = { workspace = true }
tokio-util = { workspace = true }
rand = "0.8"
futures-util = { workspace = true }
async-channel = "2"
console = "0.16"
indicatif = "0.18"
dialoguer = { workspace = true }
color-eyre = { workspace = true }
clap = { workspace = true }
clap_complete = "4"
unit-prefix = "0.5"
ctrlc = "3"
qr2term = "0.3"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
url = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = [
  'cfg(feature, values("clipboard"))',
  'cfg(feature, values("tls"))',
  'cfg(feature, values("experimental-transfer-v2"))',
] }
